### ISSUE TITLE
Add an optional parameter at the end to specify output file name

### ISSUE THREAD

**Issue by Sasino97** [xensik/gsc-tool#132]
Basically
```
gsc-tool <mode> <game> <system> <path> (output-path)
```

Example

```
gsc-tool comp t6 pc script.gsc "../../storage/t6/scripts/mp/script.gsc"
```

This would remove the tedious step of manually copying the file every time (or having to run a bat file every time)

**Comment by xensik** [comment]
will take a look, have pending to replace the current arguments with a better handling

**Comment by xensik** [comment]
i will push it for next release, also remain you plutonium is able to auto compile the files, just place the source on the desired storage/t6/.. path

**Comment by diamante0018** [comment]
Update?
