### ISSUE TITLE
iw8 .gscbin decomp error

### ISSUE THREAD

**Issue by PMac18** [xensik/gsc-tool#155]
trying to decomp any iw8 .gscbin always sends the same error: script file deserialize error at "(script path)"

iw8 .gscbin files: github.com/hc20k/iw8-rawfiles

**Comment by xensik** [comment]
you know how files got dumped? seems like they are malformed. also iw8 leaked build is not supported by public gsc-tool, only last official game version

**Comment by PMac18** [comment]
ah got it thanks. can you guide me on how to get the correct iw8 gsc script files so that I can use this tool properly?
