### ISSUE TITLE
Add Compiled GSC Expectations to README

### ISSUE THREAD

**Issue by EthanC** [xensik/gsc-tool#18]
Just want to preface this request with a thanks, you've got a really impressive project here!

I'm looking to utilize the project for some research on IW7, but I haven't found a suitable format for the scripts to provide the tool for decompilation. I think the README would be a good place to outline this.

- Should the script buffer and bytecode be in a single file? If so, which comes first and should there be padding?
- Should I decompress the compiled script?

**Comment by xensik** [comment]
- The .gscbin file format is specified here ``src/utils/xsk/gsc/asset.hpp``. Its a single file that contains: null terminated string name, 4 byte compressLen, 4 byte len, 4 byte bytecodeLen, compressed buffer and bytecode. no padding.
- The other supported format for zone-tool fastfile linker is bytecode buffer in one file ``script.cgsc``and decompresed stack buffer in other file ``script.cgsc.stack``

**Comment by EthanC** [comment]
Exactly what I was looking for, thanks!
