### ISSUE TITLE
ww2 .gscbin decomp error

### ISSUE THREAD

**Issue by sanyihun1923** [xensik/gsc-tool#194]
./gsc-tool.exe -m decomp -g S2 -s pc  D:\cod_modding\asztal\gsc_pack\ww2\scripts\896.gscbin
GSC Tool 1.4.2.291 created by xensik
[ERROR]: couldn't resolve opcode enum for '10' at D:/cod_modding/asztal/gsc_pack/ww2/scripts/896.gscbin

**Comment by xensik** [comment]
need more info, how files got dumped from memory, what game version was used / game build date?
