### ISSUE TITLE
Zonetool support

### ISSUE THREAD

**Issue by Combine900** [xensik/gsc-tool#20]
Hey,

Can we make gsc-tool compatible again with the latest public version of zonetool?
(Sadly the devs wont update zt public anymore.. and i think the current support for the gsc tool is for the private builds of zt..)

https://github.com/ZoneTool/zonetool/releases

**Comment by RektInator** [comment]
You don't need zonetool for GSC scripts. Plutonium IW5 can load GSC scripts on it's own now just like MW2. If you want to add scripts to your zone, simply add them as rawfile assets (instead of scriptfile assets).

Example: rawfile,maps/mp/gametypes/war.gsc

This will work just fine.

**Comment by Combine900** [comment]
I know.. i used it for SP.. and as we all know you guys wont do any sp modification for IW5 (sadly..)

However you can dump important SP files with zonetool and gsc-tool help us too view the .gsc code of the SP files.. but that no longer works with the current version :/

**Comment by user-45-20** [comment]
Should be an easy change to make, the binary GSCS are composed of bytecode and a stack "buffer", zonetool just dumps them to two separate files. If you look at `decompile_file` in `main.cpp`, all you really need to do is call `disassembler.disassemble` with three arguments - the file name, the bytecode buffer, and the stack buffer.

**Comment by Combine900** [comment]
> 
> 
> Should be an easy change to make, the binary GSCS are composed of bytecode and a stack "buffer", zonetool just dumps them to two separate files. If you look at `decompile_file` in `main.cpp`, all you really need to do is call `disassembler.disassemble` with three arguments - the file name, the bytecode buffer, and the stack buffer.

Sounds like a solution, but not easy to do for a noob at this stuff 😅

**Comment by xensik** [comment]
extracted sp files from zonetool should work using -z options. ``./gsc-tool.exe -iw5 -zdecomp script.cgsc``. you need both files from zonetool, script.cgsc & script.cgsc.stack

**Comment by Combine900** [comment]
> 
> 
> extracted sp files from zonetool should work using -z options. `./gsc-tool.exe -iw5 -zdecomp script.cgsc`. you need both files from zonetool, script.cgsc & script.cgsc.stack

Thank you :) hope you keep up the gud work on this tool. (btw. can you keep an eye on the SP stuff :)?)
