### ISSUE TITLE
[preprocessor]: Unreachable blocks still processed for some macros

### ISSUE THREAD

**Issue by diamante0018** [xensik/gsc-tool#201]
```c
#define TEST

#ifndef TEST
#error How did this happen
#endif

main()
{
}
```

Expected behaviour:

`#error` block should not be processed at all even though it's technically unsupported because `ifndef TEST` should never trigger because we defined `TEST` two lines before.

This is the case for C++ compilers

![image](https://github.com/xensik/gsc-tool/assets/37080671/11cce3d2-17d6-4fa9-839f-3d3a3f90ee2b)

Unexpected behaviour:

```txt
.\gsc-tool.exe -m comp -g iw5 -s pc .\a.gsc
GSC Tool 1.4.3.297-prod created by xensik
[ERROR]:preprocessor:./a.gsc:4:2: #error directive not supported at ./a.gsc
```

**Comment by diamante0018** [comment]
This still works on C++

![image](https://github.com/xensik/gsc-tool/assets/37080671/c7d06847-6774-433a-825b-c412c04a724b)

**Comment by xensik** [comment]
skip logic is parsing directives to find the #endif, or #elif. i will add skip checks to unimplemented directives
