### ISSUE TITLE
MWII GSC compile hash name function error

### ISSUE THREAD

**Issue by ProjectHiNAtyu** [xensik/gsc-tool#205]
When compiling MWII's GSC, if you compile it while including a hashed function such as the function "_id_BD1704B44A1A730E()" in the original source code, the error "stoul argument out of range at ??.gsc" occurs.
Can you fix it so that it can be compiled while leaving the functions with hashed names?
![bandicam 2024-06-02 20-47-51-596](https://github.com/xensik/gsc-tool/assets/125034349/b40e7d36-6552-41bd-ab80-508db6b33e5c)

**Comment by xensik** [comment]
i cant replicate in current version, have you edited the source code of the program?
<img width="772" alt="a" src="https://github.com/xensik/gsc-tool/assets/8714336/b30cfd3a-c1f9-43f0-bb9d-5700d8877ee5">

**Comment by xensik** [comment]
are you using 32 or 64 bits executable?
```
windows-x64-release.zip
windows-x86-release.zip 
```

**Comment by ProjectHiNAtyu** [comment]
I am using the "gsc-tool.exe" included in the unzipped "windows-x64-release.zip" of the latest version.
I am attaching the gsc and exe files where the symptoms actually occur.
https://drive.google.com/file/d/19VjcOsSBctXmwhhDWoMALOMD6HenPokW/view?usp=sharing

**Comment by xensik** [comment]
there was a bug in the compiler, will be fixed for next release #208
