### ISSUE TITLE
Unable to open program

### ISSUE THREAD

**Issue by mbestcare1** [xensik/gsc-tool#206]
When I try to use 1.4.4 Windows x86 or x64, it flashes open for a second and instantly closes. I've tried dragging and dropping files and opening as admin. There's no guides or tutorials I can find, can anyone help?

**Comment by mjkzy** [comment]
https://github.com/xensik/gsc-tool/blob/dev/README.md

**Comment by xensik** [comment]
its a command like program, you need to run inside cmd
