### ISSUE TITLE
[Decompiler] Prepending hash symbol next to defined dvar strings

### ISSUE THREAD

**Issue by Jbleezy** [xensik/gsc-tool#207]
All calls to built-in dvar functions such as `getdvar` have a `#` prepended to the string of the dvar name. I believe this should only be the case for the unknown dvar hashes, as that is how it was in a previous version of the tool.

Example:
```
level.scr_zm_ui_gametype = getdvar( #"ui_gametype" );
```
should be:
```
level.scr_zm_ui_gametype = getdvar( "ui_gametype" );
```

**Comment by ineedbots** [comment]
this is intended behavior because it is what the GSC bytecode is doing, it's passing a hash (that we know of) to the builti

we want the decompiler to produce a GSC script that when compiled produces matching bytecode to the original
