### ISSUE TITLE
Couldn't resolve instruction size for ...

### ISSUE THREAD

**Issue by realiteehee** [xensik/gsc-tool#21]
Anyone know how to fix this? Only certain .gscbin files output this error so could it be due to the file? Or am I doing something wrong?

**Comment by user-45-20** [comment]
Are you decompiling files you've compiled earlier? Or stock scriptfiles from the game itself?

**Comment by realiteehee** [comment]
> Are you decompiling files you've compiled earlier? Or stock scriptfiles from the game itself?


Scriptfiles from the game itself. That's the thing though. It works with the majority of other scriptfiles from the game, just a specific few seem to break the program.

**Comment by user-45-20** [comment]
Can you tell me which one breaks it?

**Comment by realiteehee** [comment]
> Can you tell me which one breaks it?

MW2019 br_ending.gscbin
might have some sort of other encryption, but that's the one

**Comment by xensik** [comment]
could be related to compiled string IDs, the maximum ID change between game versions. some old scripts may not work after updating the values
