### ISSUE TITLE
[Decompiler] Location not found error

### ISSUE THREAD

**Issue by Jbleezy** [xensik/gsc-tool#213]
I am getting location not found error for certain GSC's, such as T6 `_zm.gsc` from `patch_zm` fastfile.

![image](https://github.com/xensik/gsc-tool/assets/20487224/ee661d49-4673-40e7-91ae-f117330d0be1)

**Comment by xensik** [comment]
can you attach the file or send at discord?

**Comment by xensik** [comment]
#215
