### ISSUE TITLE
iw8 can't include scripts using their asset names

### ISSUE THREAD

**Issue by k0rtFx** [xensik/gsc-tool#218]
some scripts use their asset names string and won't compile when including them
example:
`init() { scripts/anim/face.gsc::initlevelface(); }`

will return the error `1:17: syntax error, unexpected /`

while using the encrypted string for the script will properly compile
`init() {
    _encstr_b282169b8de496c13acde52c9bb4b6f29958d8595c3b6e1b::initlevelface();
}`

**Comment by xensik** [comment]
gsc paths are writen with backslash '\\'. thats the syntax error
