### ISSUE TITLE
[fix: compiler]: Allow self.wait to work

### ISSUE THREAD

**Issue by diamante0018** [xensik/gsc-tool#220]
it appears on Ghosts `self.wait` is a valid token name and right now it causes a compilation error because gsc-tool parses it as a function call rather than token name.

**Comment by diamante0018** [comment]
https://github.com/xensik/gsc-tool/blob/be3abc1a763b2c64d5ace331feddd974a6baf862/src/gsc/engine/iw6_pc_token.cpp#L779

**Comment by xensik** [comment]
done  #223
