### ISSUE TITLE
Warzone pacific update breaks decompilation of various scripts

### ISSUE THREAD

**Issue by kibrookfield** [xensik/gsc-tool#24]
After the December update to MW/ Warzone a lot of scripts fail to decompile. Just to give examples of some scripts that are throwing errors:

16.gsc -> Couldn't resolve instruction size for 194
1824.gsc -> [gsc decompiler]: LOCATION NOT FOUND! (loc_1DF)
1866.gsc -> Couldn't resolve instruction size for 198
1912.gsc -> Couldn't resolve instruction size for 175
1914.gsc -> [gsc]: Couldn't resolve builtin function name for id '44512'!
1918.gsc -> WARNING: bad local var access
1923.gsc -> [gsc]: Couldn't resolve builtin function name for id '1086'!

**Comment by xensik** [comment]
Will need to update new native functions and compiled strings from recent game builds

**Comment by xensik** [comment]
should be fixed on latest release

**Comment by kibrookfield** [comment]
Indeed it works great now.
