### ISSUE TITLE
[Bug]Issues with nested folders

### ISSUE THREAD

**Issue by INSANEMODE** [xensik/gsc-tool#25]
Using latest commit ( ac2b8a65cea5c9bcfc78b5cb19c8cadc1b87eed5 ) on dev branch, and using debug build from source.
(but also happens with latest release)

When feeding gsc-tool a path that contains nested folders, it handles them in unexpected ways. 

(for this, i am using the scripts extracted from t6's zm_tomb_patch.ff)

[compiled_scripts_dir.txt](https://github.com/xensik/gsc-tool/files/8222642/compiled_scripts_dir.txt)

For example, when using this command:
`C:\Users\scott\source\bo2 resources\gsc-tool>.\gsc-tool.exe decomp t6 "C:\Users\scott\source\bo2 resources\gsc-tool\maps
" > output.txt 2>&1
`
[output.txt](https://github.com/xensik/gsc-tool/files/8222559/output.txt)

If you have say, /maps/mp/(gsc files)  with maps only containing the mp folder, the decompiled folder will contain `\t6\maps\mp`

with mp being a file, with no extension, and contains the decompiled script for the last file in the folder, alphabetically, i assume? 

It essentially skips all scripts aside from the last one found, and names it the nested folder name. 
//

Another example.
Say you remove the maps folder.  you end up with nested folders like `\mp\animscripts\traverse\`, but this time, the mp folder has other files and folders in the same directory as the nested folder.
and like the last one, animscripts is empty aside from the traverse folder.

The behavior is a bit different in this situation.

`C:\Users\scott\source\bo2 resources\gsc-tool>.\gsc-tool.exe decomp t6 "C:\Users\scott\source\bo2 resources\gsc-tool\mp" > output_2.txt 2>&1`

[output_2.txt](https://github.com/xensik/gsc-tool/files/8222764/output_2.txt)

In this case, you end up with the file`\decompiled\t6\animscripts\traverse `, with it containing the script for the last file in the `\mp\animscripts\traverse\` folder.  but in this case, all other folders and files in the specified path will be decompiled in place, rather than keeping the original files, and putting the decompiled scripts in the decompiled folder.

I haven't done any other testing than this. (haven't checked other modes, files, or folders, or what happens if gsc-tool is in a different filepath or drive from the compiled scripts)

**Comment by xensik** [comment]
I added a function to extract the game file path starting at game data root. if you remove the maps folder, it uses the entire path since "mp" is not present in the game root folder. seems like file name is not append in some cases.

Also, the first path u used have a space at the end
<img width="1105" alt="Captura de pantalla 2022-03-10 a las 12 51 20" src="https://user-images.githubusercontent.com/8714336/157657237-599388ed-a4d5-4324-8c31-78fffa4fefc3.png">
works for me, could be a problem of std::filesystem different in clang vs msvc

**Comment by xensik** [comment]
I recommend you use gsc-tool on the root of game data and use relative paths
``gsc-tool decomp t6 ./maps``
``gsc-tool decomp t6 ./codescripts``
``gsc-tool comp t6 ./maps/mp/mp_test.gsc``
this way, file path that is writen inside the script have the same root as other files in the game database

**Comment by INSANEMODE** [comment]
alright. re-did some tests with your suggestions. using the latest release on github, and the debug build i built. zero difference in behavior, using relative path, or release build downloaded from github.

 gsc-tool is in the same folder as my maps folder. (same as it was in my original post)
used relative path. 

`gsc-tool_1_0_225.exe decomp t6 ./maps`
[output.txt](https://github.com/xensik/gsc-tool/files/8230038/compiled_scripts.txt)


[decompiled_dir.txt](https://github.com/xensik/gsc-tool/files/8230062/decompiled_dir.txt)

try testing on your end using this, and see if you can reproduce the issue.

[test_scripts.zip](https://github.com/xensik/gsc-tool/files/8230091/test_scripts.zip)

if i remove both instances of nested folders (removed maps folder, compiling from ./mp, and deleting animscripts folder , it works fine.

`gsc-tool_1_0_225.exe decomp t6 ./mp`
[output2.txt](https://github.com/xensik/gsc-tool/files/8230149/compiled_scripts.txt)

[decompiled_dir2.txt](https://github.com/xensik/gsc-tool/files/8230148/decompiled_dir.txt)

**Comment by INSANEMODE** [comment]
ah, i see the issue.

https://github.com/xensik/gsc-tool/blob/ac2b8a65cea5c9bcfc78b5cb19c8cadc1b87eed5/src/t6/xsk/resolver.cpp#L136
in this function, ` result /= entry;` makes maps\mp, which isn't in https://github.com/xensik/gsc-tool/blob/ac2b8a65cea5c9bcfc78b5cb19c8cadc1b87eed5/src/t6/xsk/resolver.cpp#L103

it only has maps/mp, so this https://github.com/xensik/gsc-tool/blob/ac2b8a65cea5c9bcfc78b5cb19c8cadc1b87eed5/src/t6/xsk/resolver.cpp#L148 is not true on the next iteration, when `maps\mp` is the argument.

![image](https://user-images.githubusercontent.com/10606102/157838594-20bf79c5-1e99-48a6-99d3-787c9ea02175.png)


going in and adding `\\` versions of the paths to the list fixes the issue, and everything seems to decompile just fine. 
![image](https://user-images.githubusercontent.com/10606102/157838920-fbbbfe69-de34-4d36-a1c9-48adb96bddf5.png)


made #26 to resolve the problem.

**Comment by xensik** [comment]
windows uses backslash for std::filesystem::path. instead of duplicating the folder entries just make use of generic path
