### ISSUE TITLE
decompile problem

### ISSUE THREAD

**Issue by Combine900** [xensik/gsc-tool#44]
Hey, is there a reason that you cant decompile iw5(pc) zonetool .cgsc files?

If i try too use "gsc-tool decomp iw5 ally_so_delta.cgsc"  i get this "error" - "expected .gscbin file at ally_so_delta.cgsc"

**Comment by xensik** [comment]
use the z options "gsc-tool zdecomp iw5 ally_so_delta.cgsc" for zonetool

**Comment by xensik** [comment]
https://github.com/xensik/gsc-tool#usage
