### ISSUE TITLE
add names iw6 

### ISSUE THREAD

**Issue by xHouxanx** [xensik/gsc-tool#45]
hi
maybe check this for iw6 correct  and add name
_id_6B55,script_bombmode_original
_id_6CCF,script_targetoffset_z , this maybe ok
_id_6B19,script_accel
_id_6B24,script_airspeed
_id_4FB0,ltorigin
_id_6109,precache_script
_id_7703,sound_csv_include
_id_4E11,lighttargetname

**Comment by diamante0018** [comment]
how did you find these names?

**Comment by xHouxanx** [comment]
> how did you find these names?
compare same in iw5 and iw6 mapents
