### ISSUE TITLE
Can't build for Linux on Pop! OS

### ISSUE THREAD

**Issue by LucasStf** [xensik/gsc-tool#79]
Hello, i want to use the gsc-tool on linux, so i've downloaded the git repository and execute the prebuild-linux.sh, and when i try to build the project on linux using make(Pop! OS), i have this error :

strafe@pop-os:~/Documents/Dev/cpp/gsc-tool/build$ make
==== Building xsk-utils (debug_x86) ====
==== Building xsk-gsc (debug_x86) ====
assembler.cpp
In file included from ../src/gsc/misc/types.hpp:11,
                 from ../src/gsc/assembler.hpp:8,
                 from ../src/gsc/assembler.cpp:7:
../src/gsc/misc/assembly.hpp:229:12: error: declaration of ‘xsk::gsc::opcode xsk::gsc::instruction::opcode’ changes meaning of ‘opcode’ [-fpermissive]
  229 |     opcode opcode;
      |            ^~~~~~
../src/gsc/misc/assembly.hpp:13:12: note: ‘opcode’ declared here as ‘enum class xsk::gsc::opcode’
   13 | enum class opcode : u8
      |            ^~~~~~
In file included from ../src/gsc/assembler.cpp:8:
../src/gsc/context.hpp:25:10: error: declaration of ‘xsk::gsc::props xsk::gsc::context::props() const’ changes meaning of ‘props’ [-fpermissive]
   25 |     auto props() const -> props { return props_; }
      |          ^~~~~
In file included from ../src/gsc/assembler.hpp:8,
                 from ../src/gsc/assembler.cpp:7:
../src/gsc/misc/types.hpp:63:8: note: ‘props’ declared here as ‘struct xsk::gsc::props’
   63 | struct props
      |        ^~~~~
make[1]: *** [xsk-gsc.make:181 : obj/debug/xsk-gsc/x86/assembler.o] Erreur 1
make: *** [Makefile:134 : xsk-gsc] Erreur 2

**Comment by xensik** [comment]
linux support not finished, linux build on CI still pending

**Comment by xensik** [comment]
had some problems with gcc / premake

**Comment by diamante0018** [comment]
Linux build is supported as of a few minutes ago:
https://github.com/xensik/gsc-tool/pull/81
